### ISSUE TITLE
Add AJP support to vhost

### ISSUE THREAD

**Issue by mkruliv** [IF-061-DevOps/OMS-ansible#70]
@BrunIF Додай будь ласка підтримку AJP до virtual hosts файлу (Apache2 Role). Необхідно в залежності від потреби додавати блок:

```
<Proxy *>
      AddDefaultCharset Off
      Order deny,allow
      Allow from all
</Proxy>
ProxyPass / ajp://{{ vhost_name }}.{{ ansible_all_ipv4_addresses[0] }}.xip.io:8009/
ProxyPassReverse / ajp://{{ vhost_name }}.{{ ansible_all_ipv4_addresses[0] }}.xip.io:8009/
```

**Comment by ipleten** [comment]
там має бути локалхост. апач стоїть на тому ж самому хості.

**Comment by mkruliv** [comment]
{% if inventory_hostname in groups['webapp'] %}
<Proxy *>
      AddDefaultCharset Off
      Order deny,allow
      Allow from all
</Proxy>
ProxyPass / ajp://localhost:8009/
ProxyPassReverse / ajp://localhost:8009/
{% endif %}

**Comment by mkruliv** [comment]
Added in[ Pull # 78 ](https://github.com/IF-061-DevOps/OMS-ansible/pull/78)
